object = 'LumpedElement'

[[imports]]
module = 'typing'
attribute = 'Optional'

[[enums]]
name = 'Type'
values = [
    { name = 'RLC_PARALLEL', value = 'rlcparallel' },
    { name = 'RLC_SERIAL', value = 'rlcserial' },
    'diode',
    { name = 'SPICE_CIRCUIT', value = 'spicecircuit' },
    'touchstone',
    { name = 'MULTIPIN_GROUP_ITEM', value = 'multipingroupitem' },
    { name = 'MULTIPIN_GROUP_SPICE', value = 'multipingroupspice' },
    { name = 'MULTIPIN_GROUP_TOUCHSTONE', value = 'multipingrouptouchstone' },
]

[[methods]]
name = 'Reset'
cache = true

[[methods]]
name = 'Create'
cache = true
flush_cache = 'Create LumpedElement'

[[methods]]
name = 'CreateMultipin'
cache = true
flush_cache = 'CreateMultipin LumpedElement'

[[methods]]
name = 'Modify'
cache = true
flush_cache = 'Modify LumpedElement'

[[methods]]
name = 'SetType'
cache = true
args = [
    { name = 'elem_type', type = 'Type' },
]

[[methods]]
name = 'SetName'
cache = true
args = [
    { name = 'name', type = 'str' },
]

[[methods]]
name = 'Folder'
py_name = 'set_folder_name'
cache = true
args = [
    { name = 'folder_name', type = 'str' },
]

[[methods]]
name = 'SetR'
py_name = 'set_resistance'
cache = true
args = [
    { name = 'value', type = 'float' },
]

[[methods]]
name = 'SetL'
py_name = 'set_inductance'
cache = true
args = [
    { name = 'value', type = 'float' },
]

[[methods]]
name = 'SetC'
py_name = 'set_capacitance'
cache = true
args = [
    { name = 'value', type = 'float' },
]

[[methods]]
name = 'SetGs'
py_name = 'set_blocking_conductivity'
cache = true
args = [
    { name = 'value', type = 'float' },
]

[[methods]]
name = 'SetI0'
py_name = 'set_reverse_current'
cache = true
args = [
    { name = 'value', type = 'float' },
]

[[methods]]
name = 'SetT'
py_name = 'set_temperature_kelvin'
cache = true
args = [
    { name = 'value', type = 'float' },
]

[[methods]]
name = 'SetT'
py_name = 'set_temperature_celsius'
cache = true
args = [
    { name = 'value', type = 'float' },
]
vba_call_args = ['value-273.15']

[[methods]]
name = 'SetT'
py_name = 'set_temperature_fahrenheit'
cache = true
args = [
    { name = 'value', type = 'float' },
]
vba_call_args = ['(value + 459.67)*(5/9)']

[[methods]]
name = 'SetP1'
py_name = 'set_point1'
cache = true
args = [
    { name = 'coords', type = 'float', dimension = 3 },
]
vba_call_args = [false, 'coords[0]', 'coords[1]', 'coords[2]']

[[methods]]
name = 'SetP1'
py_name = 'set_pick_as_point1'
cache = true
vba_call_args = [true, 0, 0, 0]

[[methods]]
name = 'SetP2'
py_name = 'set_point2'
cache = true
args = [
    { name = 'coords', type = 'float', dimension = 3 },
]
vba_call_args = [false, 'coords[0]', 'coords[1]', 'coords[2]']

[[methods]]
name = 'SetP2'
py_name = 'set_pick_as_point2'
cache = true
vba_call_args = [true, 0, 0, 0]

[[methods]]
name = 'GetCoordinates'
return_type = { __retval__ = 'Boolean', x0 = 'Double', y0 = 'Double', z0 = 'Double', x1 = 'Double', y1 = 'Double', z1 = 'Double' }
args = [
    { name = 'name', type = 'str' },
    { name = 'x0', type = '__retval__' },
    { name = 'y0', type = '__retval__' },
    { name = 'z0', type = '__retval__' },
    { name = 'x1', type = '__retval__' },
    { name = 'y1', type = '__retval__' },
    { name = 'z1', type = '__retval__' },
]
python_return_type = 'Optional[Tuple]'
map_return_value = 'None if not __retval__[0] else tuple(__retval__[1:])'
return_value_description = """
coordinates
    (x0, y0, z0, x1, y1, z1) *on success* | None
"""

[[methods]]
name = 'GetProperties'
return_type = { __retval__ = 'Boolean', type = 'String', r = 'Double', l = 'Double', c = 'Double', gs = 'Double', i0 = 'Double', t = 'Double', radius = 'Double' }
args = [
    { name = 'name', type = 'str' },
    { name = 'type', type = '__retval__' },
    { name = 'r', type = '__retval__' },
    { name = 'l', type = '__retval__' },
    { name = 'c', type = '__retval__' },
    { name = 'gs', type = '__retval__' },
    { name = 'i0', type = '__retval__' },
    { name = 't', type = '__retval__' },
    { name = 'radius', type = '__retval__' },
]
python_return_type = 'Optional[Tuple]'
map_return_value = 'None if not __retval__[0] else tuple(__retval__[1:])'
return_value_description = """
properties
    (type, r, l, c, Gs, I0, T, radius) *on success* | None
"""

[[methods]]
name = 'CircuitFileName'
py_name = 'set_circuit_file_name'
cache = true
args = [
    { name = 'file_name', type = 'str' },
]

[[methods]]
name = 'UseRelativePath'
py_name = 'set_use_relative_path'
cache = true
args = [
    { name = 'flag', type = 'bool' },
]

[[methods]]
name = 'CircuitId'
py_name = 'set_circuit_id'
cache = true
args = [
    { name = 'id', type = 'int' },
]

[[methods]]
name = 'UseCopyOnly'
py_name = 'set_use_copy_only'
cache = true
args = [
    { name = 'flag', type = 'bool' },
]

[[methods]]
name = 'SetInvert'
cache = true
args = [
    { name = 'flag', type = 'bool' },
]

[[methods]]
name = 'SetMonitor'
cache = true
args = [
    { name = 'flag', type = 'bool' },
]

[[methods]]
name = 'SetRadius'
cache = true
args = [
    { name = 'radius', type = 'float' },
]

[[methods]]
name = 'Wire'
py_name = 'set_wire'
cache = true
args = [
    { name = 'wire', type = 'str' },
]

[[methods]]
name = 'Position'
py_name = 'set_wire_end_to_end1'
cache = true
vba_call_args = ["'end1'"]

[[methods]]
name = 'Position'
py_name = 'set_wire_end_to_end2'
cache = true
vba_call_args = ["'end2'"]

[[methods]]
name = 'PortName'
py_name = 'set_port_name'
cache = true
args = [
    { name = 'name', type = 'str' },
]

[[methods]]
name = 'StartLumpedElementNameIteration'
py_name = 'start_name_iteration'

[[methods]]
name = 'ConnectMultipinElementPinToSubElement'
args = [
    { name = 'multipin_name', type = 'str' },
    { name = 'circuit_pin_name', type = 'str' },
    { name = 'multipin_sub_element_name', type = 'str' },
]

[[methods]]
name = 'ConnectMultipinElementPinToShort'
args = [
    { name = 'multipin_name', type = 'str' },
    { name = 'circuit_pin_name', type = 'str' },
]

[[methods]]
name = 'ConnectMultipinElementPinToOpen'
args = [
    { name = 'multipin_name', type = 'str' },
    { name = 'circuit_pin_name', type = 'str' },
]

[[methods]]
name = 'GetNextLumpedElementName'
py_name = 'get_next_name'

[[methods]]
name = 'Rename'
args = [
    { name = 'old_name', type = 'str' },
    { name = 'new_name', type = 'str' },
]

[[methods]]
name = 'Delete'
args = [
    { name = 'name', type = 'str' },
]

[[methods]]
name = 'NewFolder'
py_name = 'create_folder'
args = [
    { name = 'name', type = 'str' },
]

[[methods]]
name = 'DeleteFolder'
args = [
    { name = 'name', type = 'str' },
]

[[methods]]
name = 'RenameFolder'
args = [
    { name = 'old_name', type = 'str' },
    { name = 'new_name', type = 'str' },
]
